### ISSUE TITLE
KeyError   mail_enable

### ISSUE THREAD

**Issue by heh3** [zj1244/beholder_scanner#3]
scanner目录下缺少可写的setting.json文件
在web端配置邮件发送后会报KeyError   mail_enable错误

**Comment by zj1244** [comment]
@heh3 抱歉那么久才看到消息。问下这个错误是web端的还是scanner端的？方便截图看下吗

**Comment by heh3** [comment]
git里拉的项目，scanner下默认没有seting.json这个文件，web端配置完成后，scanner不能将读取到配置写入到setting.json文件中，在scanner目录下建一个空的seting.json文件后可以正常发送邮件

**Comment by zj1244** [comment]
默认scanner里的是没有setting.json，如果在web端配置后，就会生成了setting.json了

**Comment by zj1244** [comment]
你是用docker搭建的web还是用源码？

**Comment by heh3** [comment]
web源码，centos7，root用户，配置完没有自动生成setting.json文件，应该是权限的问题，还需要给setting.json文件设置可写权限

**Comment by heh3** [comment]
[好像还是有bug，之前修改setting文件后，有几封邮件发送成功了，现在我在web上修改了线程数，邮件密码都是对的，但是又报了这个错，邮件也发送失败了，但是setting文件没有跟着同步更新
[https://ae01.alicdn.com/kf/Hed40a672d3774d19a93594d9bfdf126fv.jpg](url)

**Comment by heh3** [comment]
问题找到了，没有在beholder_scanner目录下启动main.py 导致根据scanner/setting.json路径找不到setting.json，获取不了邮件配置造成的发送失败～

**Comment by zj1244** [comment]
已经修复了这个bug，现在不在beholder_scanner目录下启动main.py 也不会出现这个问题了

issue:fix by commit 8319d29
